server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/campus_job_hub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: campusjobhub
    password: campusjobhub123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

